// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDB))]
    [Migration("20250125195302_Seeding data into Categories")]
    partial class SeedingdataintoCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc0d1735-34ef-441d-84b3-a9f8fdfa58ab"),
                            Description = "Smesne knjige",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("f147a008-a693-4c37-b99c-379e3e89a38e"),
                            Description = "Knjige koje imaju pouno uzbudljivih dogadjaja",
                            Name = "Akcioni"
                        },
                        new
                        {
                            Id = new Guid("8ec37b41-9c77-4311-8463-ac8d8820cb19"),
                            Description = "Knjige u kojima je prica neizvesna",
                            Name = "Trejler"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
