// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDB))]
    [Migration("20250125221128_Adding Category navigator into Product")]
    partial class AddingCategorynavigatorintoProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc0d1735-34ef-441d-84b3-a9f8fdfa58ab"),
                            Description = "Smesne knjige",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("f147a008-a693-4c37-b99c-379e3e89a38e"),
                            Description = "Knjige koje imaju pouno uzbudljivih dogadjaja",
                            Name = "Akcioni"
                        },
                        new
                        {
                            Id = new Guid("8ec37b41-9c77-4311-8463-ac8d8820cb19"),
                            Description = "Knjige u kojima je prica neizvesna",
                            Name = "Trejler"
                        });
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6da3390d-045c-466f-a721-c208151a0457"),
                            Author = "Billy Spark",
                            CategoryId = new Guid("8ec37b41-9c77-4311-8463-ac8d8820cb19"),
                            Description = "ss",
                            ISBN = "SWD9999001",
                            Price = 90.0,
                            Title = "Fortune of Time"
                        },
                        new
                        {
                            Id = new Guid("766671fc-ef63-4100-abbf-0ce086a57b3b"),
                            Author = "Nancy Hoover",
                            CategoryId = new Guid("bc0d1735-34ef-441d-84b3-a9f8fdfa58ab"),
                            Description = "sss",
                            ISBN = "CAW777777701",
                            Price = 30.0,
                            Title = "Dark Skies"
                        },
                        new
                        {
                            Id = new Guid("c8bf5a09-45dc-45fb-8156-e6aaf7fd237e"),
                            Author = "Julian Button",
                            CategoryId = new Guid("bc0d1735-34ef-441d-84b3-a9f8fdfa58ab"),
                            Description = "ss",
                            ISBN = "RITO5555501",
                            Price = 50.0,
                            Title = "Vanish in the Sunset"
                        },
                        new
                        {
                            Id = new Guid("23818011-d27b-47d5-8d39-0083eef89022"),
                            Author = "Abby Muscles",
                            CategoryId = new Guid("f147a008-a693-4c37-b99c-379e3e89a38e"),
                            Description = "ll ",
                            ISBN = "WS3333333301",
                            Price = 65.0,
                            Title = "Cotton Candy"
                        },
                        new
                        {
                            Id = new Guid("6d350160-fdfa-43cb-96c2-cd06f6c0bde6"),
                            Author = "Ron Parker",
                            CategoryId = new Guid("f147a008-a693-4c37-b99c-379e3e89a38e"),
                            Description = "kkk",
                            ISBN = "SOTJ1111111101",
                            Price = 27.0,
                            Title = "Rock in the Ocean"
                        },
                        new
                        {
                            Id = new Guid("5089ecfb-17b8-4651-aca9-1036db06cee4"),
                            Author = "Laura Phantom",
                            CategoryId = new Guid("8ec37b41-9c77-4311-8463-ac8d8820cb19"),
                            Description = "oo ",
                            ISBN = "FOT000000001",
                            Price = 23.0,
                            Title = "Leaves and Wonders"
                        });
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.HasOne("Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
